# spark-pi.yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-example
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "ddcj/spark-hs:4.0.1"  # Ensure this image exists and is accessible
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.13-4.0.1.jar"
  arguments:
    - "6000"  # Number of samples for Pi calculation
  sparkVersion: "4.0.1"
  restartPolicy:
    type: Never

  
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://spark-logs/"
    "spark.hadoop.fs.s3a.endpoint": "http://minio.lakehouse.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.access.key": "admin"
    "spark.hadoop.fs.s3a.secret.key": "password"

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 4.0.1
    serviceAccount: spark-operator-spark  # Ensure this ServiceAccount exists in K8s
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0

