apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: voice-silver-populate-topic
  namespace: default
spec:

  type: Java
  mode: cluster
  image: "ddcj/spark-kafka:omea-pocv2"
  mainClass: VoiceSilverStream
  mainApplicationFile: "local:///opt/spark/apps/app.jar"
  arguments:
    - "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
    - "voice-bronze-cdr"
    - "voice-silver-cdr"
    - "s3a://spark-logs/checkpoints/voice-silver-cdr"
      
  sparkVersion: "4.0.1"  
  deps:
    packages:
      - "org.apache.spark:spark-sql-kafka-0-10_2.13:4.0.1"

  restartPolicy:
    type: Never

  sparkConf:
    "spark.jars.ivy": "/tmp/.ivy"
    
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "s3a://spark-logs/"

    "spark.hadoop.fs.s3a.endpoint": "http://minio.lakehouse.svc.cluster.local:9000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.access.key": "admin"
    "spark.hadoop.fs.s3a.secret.key": "password"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"

  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-operator-spark
    # Injecting Secret as Env Vars
    envFrom:
      - secretRef:
          name: minio-creds
    # Mapping Env Vars to Spark Properties
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: AWS_REGION
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: AWS_REGION

  executor:
    cores: 1
    instances: 1
    memory: "512m"
    # Executors need the credentials too!
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: AWS_ACCESS_KEY_ID 
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: AWS_REGION 