apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdr-data-pvc
  namespace: app
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr-generator
  namespace: app
  labels:
    app: cdr-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdr-generator
  template:
    metadata:
      labels:
        app: cdr-generator
    spec:
      containers:
        - name: cdr-generator
          image: ddcj/cdr-generator:v2
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: SFTP_HOST
              value: "fileserver"
            - name: SFTP_PORT
              value: "2222"
            - name: SFTP_USER
              value: "foo"
            - name: SFTP_PASS
              value: "passwordSftp"
            - name: SFTP_PATH
              value: "/upload"                                          
          ports:
            - containerPort: 8501
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: cdr-data
              mountPath: /app/cdr_data
      volumes:
        - name: cdr-data
          persistentVolumeClaim:
            claimName: cdr-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cdr-generator
  namespace: app
  labels:
    app: cdr-generator
spec:
  type: NodePort
  selector:
    app: cdr-generator
  ports:
    - name: https
      port: 8501
      targetPort: 8501
      nodePort: 30501