---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr-generator
  namespace: artefact
  labels:
    app: cdr-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdr-generator
  template:
    metadata:
      labels:
        app: cdr-generator
    spec:
      containers:
        - name: cdr-generator
          image: ddcj/cdr-generator:v2.4
          envFrom:
          - secretRef:
              name: "minio-creds"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: SFTP_HOST
              value: "fileserver.artefact.svc.cluster.local"
            - name: SFTP_PORT
              value: "9222"
            - name: SFTP_USER
              value: "foo"
            - name: SFTP_PASS
              value: "passwordSftp"
            - name: SFTP_PATH
              value: "/upload"                                          
          ports:
            - containerPort: 8501
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: cdr-data
              mountPath: /app/cdr_data
      volumes:
        - name: cdr-data
          emptyDir:
            sizeLimit: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: cdr-generator
  namespace: artefact
  labels:
    app: cdr-generator
spec:
  type: ClusterIP
  selector:
    app: cdr-generator
  ports:
    - name: https
      port: 8501
      targetPort: 8501
      # nodePort: 30501