apiVersion: apps/v1
kind: Deployment
metadata:
  name: iceberg-rest
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iceberg-rest
  template:
    metadata:
      labels:
        app: iceberg-rest
    spec:
      # Init Container: Replaces Docker "depends_on" 
      # It pings the DB port until it responds
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -vz db-postgresql 5432; do echo "waiting for database..."; sleep 2; done;']
      
      containers:
      - name: iceberg-rest
        image: tabulario/iceberg-rest
        ports:
        - containerPort: 8181
        env:
        # DB Config (Non-sensitive, kept as literals)
        - name: CATALOG_URI
          value: "jdbc:postgresql://db-postgresql:5432/iceberg_catalog"
        - name: CATALOG_JDBC_USER
          value: "iceberg"
        - name: CATALOG_JDBC_PASSWORD
          value: "iceberg_pass"
        - name: CATALOG_WAREHOUSE
          value: "s3://lakehouse/"
        - name: CATALOG_IO__IMPL
          value: "org.apache.iceberg.aws.s3.S3FileIO"
        - name: CATALOG_S3_ENDPOINT
          value: "http://minio:9000"
        - name: AWS_REGION
          value: "us-east-1"
        
        # MinIO Credentials pulled from Secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootUser
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: rootPassword
---
apiVersion: v1
kind: Service
metadata:
  name: iceberg-rest
  namespace: lakehouse
spec:
  selector:
    app: iceberg-rest
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: ClusterIP