apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdr-generator-hpa
  namespace: omea
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cdr-generator
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trino-hpa
  namespace: omea
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trino
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iceberg-rest-hpa
  namespace: omea
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iceberg-rest
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
